spring:
  application:
    name: eureka-server2
server:
  port: 9005 #端口
eureka:

  client:
   # register-with-eureka: true #是否将自己注册到注册中心
    #fetch-registry: true #是否从eureka中获取注册信息
    service-url:  #配置给Eureka client的请求地址
      defaultZone: http://127.0.0.1:8000/eureka/
